### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by mariaalouisaa** [Vasystus/TechHive#10]
Add the following to the README.md file: 
- What the project does / why the project is useful
- How users can get started with the project (GitHub Pages link)
- Who maintains and contributes to the project

**Comment by vasystus** [comment]
README file is done. I will add a link to a website later after deploying.

**Comment by mariaalouisaa** [comment]
Fantastic, I love the image! I just tried to put space between our GitHub username and actual name to see if it made it clickable, but it didn't make a difference. No problem though, really not necessary.
