### ISSUE TITLE
‘About us’ section

### ISSUE THREAD

**Issue by mariaalouisaa** [Vasystus/TechHive#3]
-See information about each member of your team so that I can know who you are

**Comment by vasystus** [comment]
Imaginary profiles or something from our real lives?

**Comment by mariaalouisaa** [comment]
HTML and CSS for this section added, ready to be pulled.
CSS still needs finishing touches.

**Comment by vasystus** [comment]
Could you add please the id="about" to this section, so I could tie it to the navigation menu?

**Comment by vasystus** [comment]
Sorry, found typos in second Garfield( it says Garfeild instead) and watchful(misspelled as watchful)

**Comment by mariaalouisaa** [comment]
Great thanks, I will correct those!
