### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by mariaalouisaa** [Vasystus/TechHive#4]
- Contact you to enquire about working with you
- A user cannot submit a form without filling out all of the mandatory fields (name, company name, email address)
- Information from the form doesn’t get submitted until the user clicks a button

**Comment by vasystus** [comment]
What kind of email should we use( one of our own or do we need to create a special one)?

**Comment by mariaalouisaa** [comment]
HTML and some CSS added for the form, branch ready to be pulled.
Still need to add "required' tags to mandatory inputs and 'aria-label' for accessibility.

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required

Need to change the button to an input type="submit' element so the form works correctly for accessibility requirements.
CS needs tweaking.

**Comment by mariaalouisaa** [comment]
The form now meets the requirements from the User Story. If you have any comments or requests on alterations to the CSS please let me know.

**Comment by vasystus** [comment]
Could you add please the id="contact" to this section, so I could tie it to navigation bar?

**Comment by mariaalouisaa** [comment]
Done for contact and about. Pull waiting for you to be merged.
