### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by vasystus** [Vasystus/TechHive#5]
Copyrights

**Comment by mariaalouisaa** [comment]
Do you want fake copyrights? Or shall we have :
'Designed, built and maintained by <a>Hallie</a> and <a>Maria</a>. Open-sourced on<a>GitHub</a>'
With links to our personal GitHub accounts and the repo?

**Comment by vasystus** [comment]
I like the second variant more. 
And also, would it be a good idea to add something like"... for the FAC, 22 training purposes"? What do you think?

**Comment by mariaalouisaa** [comment]
Yes, I like that. I'll add something like that to it. Will get the footer done today. 👍
