### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by mariaalouisaa** [Vasystus/TechHive#7]
The site should still look good whether the user browses on a mobile, tablet, or desktop device.

**Comment by vasystus** [comment]
Navigation bar, Introduction and What we do sections checked and media queries added.

**Comment by mariaalouisaa** [comment]
About us section, contact form and footer are all responsive. MQ's not needed, I used flexbox and max-width on elements to make them responsive.
If you are happy to, I think we can close this issue?

**Comment by vasystus** [comment]
Absolutely!
