### ISSUE TITLE
General Accessibility 

### ISSUE THREAD

**Issue by mariaalouisaa** [Vasystus/TechHive#8]
- Use Lighthouse to check accessibility score and make any necessary changes.
- Run through a11y checklist.
- Check colour contract on the page using Dev Tools.

**Comment by mariaalouisaa** [comment]
I ran a colour contrast check using and extension I have on chrome.
I changed the colour of the links in the footer and now all text, links and buttons pass the minimum requirement.
Only thing being flagged up is a div that I don't think is an issue.

<img width="952" alt="printscreen-techhive" src="https://user-images.githubusercontent.com/82417131/151038802-ff54efd3-35e1-4d80-97af-18bfca2f94c4.png">

**Comment by mariaalouisaa** [comment]
The Lighthouse report is 98/100 for accessibility which is great! Only thing being flagged is:
"Lists do not contain only <li> elements and script supporting elements (<script> and <template>)." - In the nav section.

I went through the Lighthouse "Additional items to manually check" and they all seem fine.

<img width="957" alt="lighthouse-report" src="https://user-images.githubusercontent.com/82417131/151039900-ea7fde27-dd03-4667-b97c-a046ba8d6b13.png">

**Comment by vasystus** [comment]
Yes, I checked it too. I think the problem is because I added the dropdown button "TechHIve" in the menu, so the Lighthouse see it like a foreign element in <ul>.
